# Generated by scripts/setup_cross_validation.sh — source before running CV.
#   source scripts/cv_env.sh

export SVZEROD_INSTALL_DIR="/Users/natalia/cursor_access/svZeroDPlus/Release"
export PATH="$SVZEROD_INSTALL_DIR:$PATH"

if [[ -f "/Users/natalia/cursor_access/learn_lpns/.venv/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source "/Users/natalia/cursor_access/learn_lpns/.venv/bin/activate"
fi

cd "/Users/natalia/cursor_access/learn_lpns"
