# Generated by scripts/setup_cross_validation.sh — do not edit by hand.
# Activates .venv, points SVZEROD_INSTALL_DIR at built solvers, cds to repo.
#
#   source scripts/cv_env.sh
#   learn-lpns-cv --set_name VMR_aortas --geometry_variant bifurcations_EL --num_trials 2

export SVZEROD_INSTALL_DIR="/Users/natalia/cursor_access/svZeroDPlus/Release"
export PATH="$SVZEROD_INSTALL_DIR:$PATH"

if [[ -f "/Users/natalia/cursor_access/learn_lpns/.venv/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source "/Users/natalia/cursor_access/learn_lpns/.venv/bin/activate"
fi

cd "/Users/natalia/cursor_access/learn_lpns"
