# Generated by scripts/setup_cross_validation.sh — do not edit by hand.
# Activates .venv, points SVZEROD_INSTALL_DIR at built solvers, cds to repo.
#
#   source scripts/cv_env.sh
#   learn-lpns-cv --set_name VMR_aorta_starter --geometry_variant bifurcations_EL --num_trials 2

export SVZEROD_INSTALL_DIR="/Users/projects/svZeroDPlus/Release"
export PATH="$SVZEROD_INSTALL_DIR:$PATH"

if [[ -f "/Users/projects/learn_lpns/.venv/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source "/Users/projects/learn_lpns/.venv/bin/activate"
fi

cd "/Users/projects/learn_lpns"
