# Generated by scripts/setup_notebook.sh — do not edit by hand.
# Activates .venv and cds to repo for Jupyter / CLI use.
#
#   source scripts/notebook_env.sh
#   jupyter notebook examples/nn_parameter_comparison.ipynb

if [[ -f "/Users/natalia/cursor_access/learn_lpns/.venv/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source "/Users/natalia/cursor_access/learn_lpns/.venv/bin/activate"
fi

cd "/Users/natalia/cursor_access/learn_lpns"
