# Generated by scripts/setup_notebook.sh — source before running the notebook.
#   source scripts/notebook_env.sh

if [[ -f "/Users/natalia/cursor_access/learn_lpns/.venv/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source "/Users/natalia/cursor_access/learn_lpns/.venv/bin/activate"
fi

cd "/Users/natalia/cursor_access/learn_lpns"
