#!/usr/bin/env bash
# Clone/build dependencies for util/zerod_calibration/run_cross_validation.py:
#   - learn_lpns (this repo + bundled sample data under data/)
#   - svZeroDPlus fork (svzerodsolver + svzerodcalibrator)
#   - Python venv with JAX and pipeline packages
#
# Usage (from anywhere):
#   ./scripts/setup_cross_validation.sh
#
# Override defaults with environment variables (see --help).

set -euo pipefail

LEARN_LPNS_REPO="${LEARN_LPNS_REPO:-https://github.com/natalia-rubio/learn_lpns.git}"
LEARN_LPNS_BRANCH="${LEARN_LPNS_BRANCH:-id_based_wiring}"
SVZEROD_REPO="${SVZEROD_REPO:-https://github.com/natalia-rubio/svZeroDPlus.git}"
SVZEROD_BRANCH="${SVZEROD_BRANCH:-J-J_wiring}"
JAX_VARIANT="${JAX_VARIANT:-jax[cpu]}"
PYTHON="${PYTHON:-python3}"
CMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE:-Release}"

SKIP_CLONE=false
SKIP_SOLVER_BUILD=false
SKIP_PYTHON=false

usage() {
  cat <<'EOF'
setup_cross_validation.sh — prepare environment for run_cross_validation.py

Install layout (default):
  <workspace>/
    learn_lpns/          this repo
    svZeroDPlus/         fork with svzerodsolver + svzerodcalibrator
    svZeroDPlus/Release/ build output (SVZEROD_INSTALL_DIR)

Steps:
  1. Clone or update learn_lpns and svZeroDPlus (unless --skip-clone)
  2. cmake build svzerodsolver and svzerodcalibrator (unless --skip-solver-build)
  3. Create .venv and pip install JAX + requirements.txt (unless --skip-python)
  4. Verify bundled sample data (data/zeroD, data/oneD/VMR)
  5. Write scripts/cv_env.sh for easy activation

Options:
  --skip-clone           Do not git clone/fetch; use existing directories
  --skip-solver-build    Skip cmake build of svZeroDPlus
  --skip-python          Skip venv creation and pip installs
  -h, --help             Show this message

Environment overrides:
  WORKSPACE_DIR          Parent of learn_lpns and svZeroDPlus (default: parent of this repo)
  LEARN_LPNS_DIR         Path to learn_lpns checkout (default: <workspace>/learn_lpns)
  SVZEROD_DIR            Path to svZeroDPlus checkout (default: <workspace>/svZeroDPlus)
  LEARN_LPNS_REPO        Git remote for learn_lpns
  LEARN_LPNS_BRANCH      Git branch for learn_lpns (default: id_based_wiring)
  SVZEROD_REPO           Git remote for svZeroDPlus fork
  SVZEROD_BRANCH         Git branch for svZeroDPlus (default: J-J_wiring)
  JAX_VARIANT            pip JAX extra, e.g. jax[cpu] or jax[cuda12] (default: jax[cpu])
  PYTHON                 Python interpreter (default: python3)

After setup:
  source scripts/cv_env.sh
  python util/zerod_calibration/run_cross_validation.py \
    --set_name VMR_aortas --geometry_variant bifurcations_EL --num_trials 2

Sample data ships in learn_lpns (5 VMR geometries). Pipeline outputs under data/
and results/ are generated on first run.
EOF
}

log() { printf '==> %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

clone_or_update() {
  local dir="$1" repo="$2" branch="$3" label="$4"
  if [[ -d "$dir/.git" ]]; then
    log "Updating $label at $dir (branch $branch)"
    git -C "$dir" fetch origin
    git -C "$dir" checkout "$branch"
    git -C "$dir" pull --ff-only origin "$branch" || true
  else
    log "Cloning $label into $dir (branch $branch)"
    git clone --branch "$branch" --depth 1 "$repo" "$dir"
  fi
}

build_svzerod() {
  local src="$1"
  local build_dir="$src/$CMAKE_BUILD_TYPE"
  need_cmd cmake

  log "Configuring svZeroDPlus in $build_dir"
  cmake -S "$src" -B "$build_dir" -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE"

  log "Building svzerodsolver and svzerodcalibrator"
  cmake --build "$build_dir" --target svzerodsolver svzerodcalibrator -j "$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)"
}

verify_sample_data() {
  local root="$1"
  local missing=0
  local check
  for check in \
    "$root/data/README.md" \
    "$root/data/zeroD/VMR_aortas/standard-0d/0076_1001.json" \
    "$root/data/oneD/VMR/0076_1001/unsteady_soln.vtp"
  do
    if [[ ! -f "$check" ]]; then
      printf '  missing: %s\n' "$check" >&2
      missing=1
    fi
  done
  if [[ "$missing" -ne 0 ]]; then
    die "Bundled sample data not found under $root/data/. Ensure learn_lpns was cloned with tracked data/ files (branch $LEARN_LPNS_BRANCH)."
  fi
  log "Sample data present under $root/data/"
}

write_cv_env() {
  local learn_lpns_dir="$1"
  local svzerod_install="$2"
  local env_file="$learn_lpns_dir/scripts/cv_env.sh"
  cat >"$env_file" <<EOF
# Generated by scripts/setup_cross_validation.sh — source before running CV.
#   source scripts/cv_env.sh

export SVZEROD_INSTALL_DIR="$svzerod_install"
export PATH="\$SVZEROD_INSTALL_DIR:\$PATH"

if [[ -f "$learn_lpns_dir/.venv/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source "$learn_lpns_dir/.venv/bin/activate"
fi

cd "$learn_lpns_dir"
EOF
  chmod +x "$env_file"
  log "Wrote $env_file"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-clone) SKIP_CLONE=true ;;
    --skip-solver-build) SKIP_SOLVER_BUILD=true ;;
    --skip-python) SKIP_PYTHON=true ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown option: $1 (try --help)" ;;
  esac
  shift
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LEARN_LPNS_DIR="${LEARN_LPNS_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
WORKSPACE_DIR="${WORKSPACE_DIR:-$(dirname "$LEARN_LPNS_DIR")}"
SVZEROD_DIR="${SVZEROD_DIR:-$WORKSPACE_DIR/svZeroDPlus}"
SVZEROD_INSTALL_DIR="$SVZEROD_DIR/$CMAKE_BUILD_TYPE"

log "Workspace: $WORKSPACE_DIR"
log "learn_lpns: $LEARN_LPNS_DIR"
log "svZeroDPlus: $SVZEROD_DIR"
log "SVZEROD_INSTALL_DIR: $SVZEROD_INSTALL_DIR"

need_cmd git
need_cmd "$PYTHON"

if ! $SKIP_CLONE; then
  if [[ ! -d "$LEARN_LPNS_DIR/.git" ]]; then
    clone_or_update "$LEARN_LPNS_DIR" "$LEARN_LPNS_REPO" "$LEARN_LPNS_BRANCH" "learn_lpns"
  else
    log "Using existing learn_lpns at $LEARN_LPNS_DIR"
    if [[ -n "${LEARN_LPNS_BRANCH:-}" ]]; then
      git -C "$LEARN_LPNS_DIR" fetch origin 2>/dev/null || true
      git -C "$LEARN_LPNS_DIR" checkout "$LEARN_LPNS_BRANCH" 2>/dev/null || true
    fi
  fi
  clone_or_update "$SVZEROD_DIR" "$SVZEROD_REPO" "$SVZEROD_BRANCH" "svZeroDPlus"
else
  log "Skipping git clone/update (--skip-clone)"
  [[ -d "$LEARN_LPNS_DIR" ]] || die "learn_lpns not found at $LEARN_LPNS_DIR"
  [[ -d "$SVZEROD_DIR" ]] || die "svZeroDPlus not found at $SVZEROD_DIR"
fi

if ! $SKIP_SOLVER_BUILD; then
  build_svzerod "$SVZEROD_DIR"
else
  log "Skipping svZeroDPlus build (--skip-solver-build)"
fi

for bin in svzerodsolver svzerodcalibrator; do
  [[ -x "$SVZEROD_INSTALL_DIR/$bin" ]] || die "$bin not found at $SVZEROD_INSTALL_DIR/$bin (build failed or wrong CMAKE_BUILD_TYPE?)"
done
log "svZeroD binaries OK: $SVZEROD_INSTALL_DIR"

if ! $SKIP_PYTHON; then
  VENV_DIR="$LEARN_LPNS_DIR/.venv"
  if [[ ! -d "$VENV_DIR" ]]; then
    log "Creating Python venv at $VENV_DIR"
    "$PYTHON" -m venv "$VENV_DIR"
  fi
  # shellcheck disable=SC1091
  source "$VENV_DIR/bin/activate"
  python -m pip install --upgrade pip
  log "Installing $JAX_VARIANT (install JAX before other deps)"
  python -m pip install -U "$JAX_VARIANT"
  log "Installing requirements.txt"
  python -m pip install -r "$LEARN_LPNS_DIR/requirements.txt"
else
  log "Skipping Python setup (--skip-python)"
fi

verify_sample_data "$LEARN_LPNS_DIR"
write_cv_env "$LEARN_LPNS_DIR" "$SVZEROD_INSTALL_DIR"

cat <<EOF

Setup complete.

  source $LEARN_LPNS_DIR/scripts/cv_env.sh

  python util/zerod_calibration/run_cross_validation.py \\
    --set_name VMR_aortas \\
    --geometry_variant bifurcations_EL \\
    --num_trials 2 \\
    --run_config gen_loss

EOF
