#!/usr/bin/env bash
# Prepare environment for examples/nn_parameter_comparison.ipynb (no svZeroDPlus).
#
# Usage (from repo root):
#   ./scripts/setup_notebook.sh           # create venv + install deps
#   ./scripts/setup_notebook.sh --launch  # setup, then open the notebook
#   make notebook                         # same as --launch
#
# Override defaults with environment variables (see --help).

set -euo pipefail

JAX_VARIANT="${JAX_VARIANT:-jax[cpu]}"
PYTHON="${PYTHON:-}"
MIN_PYTHON_VERSION="3.10"
NOTEBOOK_REL="examples/nn_parameter_comparison.ipynb"

SKIP_PYTHON=false
LAUNCH=false

usage() {
  cat <<'EOF'
setup_notebook.sh — prepare environment for nn_parameter_comparison.ipynb

Steps:
  1. Create .venv (if missing or Python < 3.10)
  2. pip install JAX, then editable learn_lpns with [dev,notebook] extras
  3. Pull Git LFS sample data (if needed) and verify bundled inputs
  4. Write scripts/notebook_env.sh for easy activation

No C++ solver required. Expected notebook runtime: ~15–30 min on CPU.

Options:
  --launch        Open the notebook in Jupyter after setup
  --skip-python   Skip venv creation and pip installs
  -h, --help      Show this message

Environment overrides:
  JAX_VARIANT     pip JAX extra, e.g. jax[cpu] or jax[cuda12] (default: jax[cpu])
  PYTHON          Python 3.10+ interpreter (auto-detected if unset)
  LEARN_LPNS_DIR  Path to learn_lpns checkout (default: parent of scripts/)

After setup:
  source scripts/notebook_env.sh
  jupyter notebook examples/nn_parameter_comparison.ipynb

Or one line:
  make notebook
EOF
}

log() { printf '==> %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

python_ok() {
  "$1" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)' >/dev/null 2>&1
}

python_version_label() {
  "$1" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")'
}

find_python() {
  if [[ -n "$PYTHON" ]]; then
    command -v "$PYTHON" >/dev/null 2>&1 || die "PYTHON not found: $PYTHON"
    python_ok "$PYTHON" || die "PYTHON=$PYTHON is older than $MIN_PYTHON_VERSION (JAX requires 3.10+)"
    printf '%s' "$PYTHON"
    return 0
  fi

  local candidates=()
  local ver
  for ver in 13 12 11 10; do
    candidates+=("python3.$ver")
    if [[ "$(uname -s)" == "Darwin" ]]; then
      candidates+=("/opt/homebrew/bin/python3.$ver" "/usr/local/bin/python3.$ver")
    fi
  done
  candidates+=("python3")

  local py
  for py in "${candidates[@]}"; do
    if command -v "$py" >/dev/null 2>&1 && python_ok "$py"; then
      printf '%s' "$py"
      return 0
    fi
  done

  die "Python $MIN_PYTHON_VERSION+ required. On macOS:
  brew install python@3.12
  PYTHON=\$(brew --prefix python@3.12)/bin/python3.12 make notebook"
}

verify_notebook_data() {
  local root="$1"
  local missing=0
  local geo name
  for geo in 0129_0000 0154_0001 0174_0000 0175_0000 0176_0000; do
    if [[ ! -f "$root/data/zeroD/VMR_aortas/standard-0d/$geo.json" ]]; then
      printf '  missing: %s\n' "$root/data/zeroD/VMR_aortas/standard-0d/$geo.json" >&2
      missing=1
    fi
    local cal_el="$root/data/zeroD/VMR_aortas/gen_loss/$geo/bifurcations_EL_calibrated_output_BloodVesselJunction.json"
    if [[ ! -f "$cal_el" ]]; then
      printf '  missing: %s\n' "$cal_el" >&2
      missing=1
    fi
    local vtp="$root/data/oneD/VMR/$geo/unsteady_soln.vtp"
    if [[ ! -f "$vtp" ]]; then
      printf '  missing: %s\n' "$vtp" >&2
      missing=1
    fi
  done
  if [[ "$missing" -ne 0 ]]; then
    die "Bundled notebook inputs not found under data/. See data/README.md."
  fi
  log "Bundled notebook data OK (5 geos: standard-0d + bifurcations_EL calibrated + 1D VTP)"
}

write_notebook_env() {
  local learn_lpns_dir="$1"
  local env_file="$learn_lpns_dir/scripts/notebook_env.sh"
  cat >"$env_file" <<EOF
# Generated by scripts/setup_notebook.sh — source before running the notebook.
#   source scripts/notebook_env.sh

if [[ -f "$learn_lpns_dir/.venv/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source "$learn_lpns_dir/.venv/bin/activate"
fi

cd "$learn_lpns_dir"
EOF
  chmod +x "$env_file"
  log "Wrote $env_file"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --launch) LAUNCH=true ;;
    --skip-python) SKIP_PYTHON=true ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown option: $1 (try --help)" ;;
  esac
  shift
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LEARN_LPNS_DIR="${LEARN_LPNS_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
NOTEBOOK_PATH="$LEARN_LPNS_DIR/$NOTEBOOK_REL"

[[ -f "$NOTEBOOK_PATH" ]] || die "Notebook not found: $NOTEBOOK_PATH"

log "learn_lpns: $LEARN_LPNS_DIR"

if ! $SKIP_PYTHON; then
  PYTHON="$(find_python)"
  log "Using Python: $PYTHON ($(python_version_label "$PYTHON"))"

  VENV_DIR="$LEARN_LPNS_DIR/.venv"
  if [[ -d "$VENV_DIR" ]]; then
    if [[ ! -x "$VENV_DIR/bin/python" ]] || ! "$VENV_DIR/bin/python" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)' >/dev/null 2>&1; then
      log "Removing existing .venv (Python < 3.10 or incomplete install)"
      rm -rf "$VENV_DIR"
    fi
  fi
  if [[ ! -d "$VENV_DIR" ]]; then
    log "Creating Python venv at $VENV_DIR"
    "$PYTHON" -m venv "$VENV_DIR"
  fi
  # shellcheck disable=SC1091
  source "$VENV_DIR/bin/activate"
  python -m pip install --upgrade pip setuptools
  log "Installing $JAX_VARIANT (install JAX before other deps)"
  python -m pip install -U "$JAX_VARIANT"
  log "Installing package (editable) with [dev,notebook] extras"
  python -m pip install -e "$LEARN_LPNS_DIR[dev,notebook]"
else
  log "Skipping Python setup (--skip-python)"
  if [[ -f "$LEARN_LPNS_DIR/.venv/bin/activate" ]]; then
    # shellcheck disable=SC1091
    source "$LEARN_LPNS_DIR/.venv/bin/activate"
  fi
fi

if [[ -x "$LEARN_LPNS_DIR/scripts/setup_git_lfs.sh" ]]; then
  "$LEARN_LPNS_DIR/scripts/setup_git_lfs.sh"
fi
verify_notebook_data "$LEARN_LPNS_DIR"
write_notebook_env "$LEARN_LPNS_DIR"

if $LAUNCH; then
  command -v jupyter >/dev/null 2>&1 || die "jupyter not found — run without --skip-python or: pip install -e \".[notebook]\""
  log "Launching Jupyter: $NOTEBOOK_REL"
  exec jupyter notebook "$NOTEBOOK_PATH"
fi

cat <<EOF

Notebook environment ready.

  source $LEARN_LPNS_DIR/scripts/notebook_env.sh
  jupyter notebook $NOTEBOOK_REL

Or: make notebook
EOF
