#!/usr/bin/env python3
"""
SimVascular centerline extraction script using the Python API.
This script loads 3D geometry generated by svVascularize and extracts centerlines
using SimVascular's VMTK centerlines tool.
"""

import sys
import os
import argparse

# Add current directory to Python path for imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

def main():
    """
    Main function to extract centerlines using SimVascular Python API.
    """
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='Extract centerlines using SimVascular')
    parser.add_argument('geo_name', help='Geometry name (e.g., tree_1)')
    parser.add_argument('set_name', help='Set name (e.g., test_set)')
    args = parser.parse_args()
    
    geo_name = args.geo_name
    set_name = args.set_name
    
    print(f"Extracting centerlines for geometry: {geo_name} in set: {set_name}")
    
    # Import SimVascular modules
    try:
        import sv
        import sv_rom_simulation
        print("Successfully imported SimVascular modules")
    except ImportError as e:
        print(f"Error importing SimVascular modules: {e}")
        print("Make sure SimVascular is properly installed and in your Python path")
        sys.exit(1)
    
    # Set up paths following svVascularize convention
    base_dir = "/Users/natalia/cursor_access/learn_lpns"
    threeD_dir = os.path.join(base_dir, "data", "threeD", set_name, geo_name)
    centerlines_output = os.path.join(threeD_dir, "centerlines_simVascular.vtp")
    
    print(f"Looking for geometry in: {threeD_dir}")
    print(f"Will save centerlines to: {centerlines_output}")
    
    # Check if the directory exists
    if not os.path.exists(threeD_dir):
        print(f"Error: Directory {threeD_dir} does not exist")
        sys.exit(1)
    
    # Look for mesh files
    mesh_dir = os.path.join(threeD_dir, "mesh")
    if not os.path.exists(mesh_dir):
        print(f"Error: Mesh directory {mesh_dir} does not exist")
        print(f"Available directories in {threeD_dir}:")
        if os.path.exists(threeD_dir):
            for item in os.listdir(threeD_dir):
                item_path = os.path.join(threeD_dir, item)
                if os.path.isdir(item_path):
                    print(f"  - {item}/")
                else:
                    print(f"  - {item}")
        sys.exit(1)
    
    # Find the main mesh file (should be a .vtu file)
    mesh_files = []
    print(f"Searching for mesh files in: {mesh_dir}")
    for root, dirs, files in os.walk(mesh_dir):
        print(f"  Directory: {root}")
        print(f"  Subdirectories: {dirs}")
        print(f"  Files: {files}")
        for file in files:
            if file.endswith('.vtu'):
                mesh_files.append(os.path.join(root, file))
    
    if not mesh_files:
        print(f"Error: No .vtu mesh files found in {mesh_dir}")
        sys.exit(1)
    
    main_mesh_file = mesh_files[0]  # Use the first mesh file found
    print(f"Using mesh file: {main_mesh_file}")
    
    # Find surface files (should be .vtp files in mesh-surfaces)
    surface_files = []
    
    # First try the standard mesh-surfaces directory
    mesh_surfaces_dir = os.path.join(mesh_dir, "mesh-surfaces")
    if os.path.exists(mesh_surfaces_dir):
        for file in os.listdir(mesh_surfaces_dir):
            if file.endswith('.vtp'):
                surface_files.append(os.path.join(mesh_surfaces_dir, file))
        print(f"Found {len(surface_files)} surface files in {mesh_surfaces_dir}")
    else:
        print(f"Standard mesh-surfaces directory not found: {mesh_surfaces_dir}")
        
        # Look for mesh-surfaces in subdirectories (like fluid_msh_0/mesh-surfaces)
        for root, dirs, files in os.walk(mesh_dir):
            if "mesh-surfaces" in dirs:
                mesh_surfaces_subdir = os.path.join(root, "mesh-surfaces")
                print(f"Found mesh-surfaces in: {mesh_surfaces_subdir}")
                for file in os.listdir(mesh_surfaces_subdir):
                    if file.endswith('.vtp'):
                        surface_files.append(os.path.join(mesh_surfaces_subdir, file))
                print(f"Found {len(surface_files)} surface files in {mesh_surfaces_subdir}")
                break
    
    print(f"Total surface files found: {len(surface_files)}")
    for sf in surface_files:
        print(f"  - {sf}")
    
    try:
        # Load the main mesh using vtk
        print("Loading main mesh...")
        import vtk
        reader = vtk.vtkXMLUnstructuredGridReader()
        reader.SetFileName(main_mesh_file)
        reader.Update()
        mesh = reader.GetOutput()
        print(f"Loaded mesh with {mesh.GetNumberOfPoints()} points and {mesh.GetNumberOfCells()} cells")
        
        # Find inlet and outlet surfaces based on cap area
        # The largest cap is the inlet, all others are outlets
        cap_surfaces_with_areas = []
        
        # Filter to only cap surfaces (exclude wall surfaces)
        cap_surface_files = [f for f in surface_files if 'cap_' in os.path.basename(f)]
        
        if not cap_surface_files:
            print("Warning: No cap surfaces found, checking all surfaces")
            cap_surface_files = [f for f in surface_files if 'wall_' not in os.path.basename(f)]
        
        # Calculate area for each cap surface
        for surface_file in cap_surface_files:

            reader = vtk.vtkXMLPolyDataReader()
            reader.SetFileName(surface_file)
            reader.Update()
            polydata = reader.GetOutput()
            
            # Calculate surface area
            mass_props = vtk.vtkMassProperties()
            mass_props.SetInputData(polydata)
            mass_props.Update()
            area = mass_props.GetSurfaceArea()
            
            cap_surfaces_with_areas.append({
                'file': surface_file,
                'area': area,
                'polydata': polydata
            })
            print(f"Cap {os.path.basename(surface_file)}: area = {area:.6f}")

        
        if not cap_surfaces_with_areas:
            raise ValueError("No valid cap surfaces found to determine inlet/outlets")
        
        # Sort by area (largest first)
        cap_surfaces_with_areas.sort(key=lambda x: x['area'], reverse=True)
        
        # Largest cap is inlet, rest are outlets
        inlet_surface = cap_surfaces_with_areas[0]
        outlet_caps = cap_surfaces_with_areas[1:]
        
        inlet_surfaces = [inlet_surface['file']]
        outlet_surfaces = [cap['file'] for cap in outlet_caps]
        
        print(f"Selected largest cap as inlet: {os.path.basename(inlet_surfaces[0])} (area = {inlet_surface['area']:.6f})")
        print(f"Found {len(outlet_surfaces)} outlet surfaces")
        
        # Use already-loaded polydata for inlet and outlets
        inlet_polydata = inlet_surface['polydata']
        outlet_polydata_list = [cap['polydata'] for cap in outlet_caps]
        
        print(f"Using inlet surface: {os.path.basename(inlet_surfaces[0])}")
        for i, cap in enumerate(outlet_caps):
            print(f"Using outlet surface {i+1}: {os.path.basename(cap['file'])}")
        
        if not inlet_polydata or not outlet_polydata_list:
            print("Error: Could not load sufficient inlet/outlet surfaces for centerline extraction")
            sys.exit(1)
        
        # Create VMTK centerlines using the correct SimVascular API
        print("Creating VMTK centerlines...")

        print("Extracting surface from volume mesh...")
        surface_extractor = vtk.vtkGeometryFilter()
        surface_extractor.SetInputData(mesh)
        surface_extractor.Update()
        surface_mesh = surface_extractor.GetOutput()
        print(f"Extracted surface with {surface_mesh.GetNumberOfPoints()} points and {surface_mesh.GetNumberOfCells()} cells")
        
        # Create a model from the surface mesh
        print("Creating model from surface...")
        model = sv.modeling.PolyData()
        model.set_surface(surface_mesh)
        
        # Compute boundary faces to identify caps
        print("Computing boundary faces...")
        model.compute_boundary_faces(80)
        
        # Get face IDs and identify caps
        caps = model.identify_caps()
        

        caps = model.identify_caps()
        ids = model.get_face_ids()
        walls = [ids[i] for i,x in enumerate(caps) if not x]
        while len(walls) > 1:
            target = walls[0]
            lose = walls[1]
            model.combine_faces(target,[lose])
            #combined = mesh_utils.combine_faces(model.get_polydata(),target,lose)
            #model.set_surface(combined)
            ids = model.get_face_ids()
            caps = model.identify_caps()
            walls = [ids[i] for i,x in enumerate(caps) if not x]
            print(walls)
        ids = model.get_face_ids()

        num_caps = 7
        if len(ids) > 1 + num_caps:
            face_cells = []
            for idx in ids:
                face = model.get_face_polydata(idx)
                cells = face.GetNumberOfCells()
                print(cells)
                face_cells.append(cells)
            data_to_remove = len(ids) - 1 - num_caps
            remove_list = []
            for i in range(data_to_remove):
                remove_list.append(ids[face_cells.index(min(face_cells))])
                face_cells[face_cells.index(min(face_cells))] += 1000
            print(remove_list)
            while len(remove_list) > 0:
                target = walls[0]
                lose = remove_list.pop(-1)
                model.combine_faces(target,[lose])
                #combined = mesh_utils.combine_faces(model.get_polydata(),target,lose)
                #model.set_surface(combined)
                print(remove_list)
            print(model.get_face_ids())
        
        # Identify inlet and outlet faces
        inlet_face_id = None
        outlet_face_ids = []
        
        # Find the largest cap as inlet (typically the main vessel)
        cap_areas = []
        for i, face_id in enumerate(ids):
            if caps[i]:  # This is a cap
                face_polydata = model.get_face_polydata(face_id)
                # Calculate area
                mass_props = vtk.vtkMassProperties()
                mass_props.SetInputData(face_polydata)
                mass_props.Update()
                area = mass_props.GetSurfaceArea()
                cap_areas.append((face_id, area))
        assert len(cap_areas) == num_caps
        # Sort by area (largest first)
        cap_areas.sort(key=lambda x: x[1], reverse=True)
        print(f"Cap areas: {cap_areas}")
        
        # Use the largest cap as inlet, others as outlets
        if cap_areas:
            inlet_face_id = cap_areas[0][0]  # Largest cap
            outlet_face_ids = [cap[0] for cap in cap_areas[1:]]  # Rest as outlets
            print(f"Inlet face ID: {inlet_face_id}")
            print(f"Outlet face IDs: {outlet_face_ids}")
        
        if inlet_face_id is None or not outlet_face_ids:
            raise Exception("Could not identify inlet and outlet faces")
        
        # Generate centerlines using the correct VMTK API
        print("Generating centerlines with VMTK...")
        cent_solid = sv.modeling.PolyData()
        centerlines_mesh = sv.vmtk.centerlines(
            model.get_polydata(), 
            inlet_ids=[inlet_face_id], 
            outlet_ids=outlet_face_ids, 
            use_face_ids=True
        )
        cent_solid.set_surface(centerlines_mesh)
        cent_solid.write(os.path.join(threeD_dir, "centerlines_simVascular"), "vtp")
        print("✅ VMTK centerlines generated successfully!")

    except Exception as e:
        print(f"Error during centerlines extraction: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
